### ISSUE TITLE
Not able to run Nitrate using images

### ISSUE THREAD

**Issue by 5ach1n** [Nitrate/Nitrate#1065]
Steps followed : 

1. Cloned repository
2. cd /Nitrate
3. Run command docker-compose -f container-compose.yml up
4. Geting below error in logs when I navigate to http://127.0.0.1:8001/

`nitrate-messagebus-1  | 2022-03-30 21:54:00.623 [info] <0.877.0> accepting AMQP connection <0.877.0> (172.18.0.4:57504 -> 172.18.0.2:5672)
nitrate-messagebus-1  | 2022-03-30 21:54:00.629 [info] <0.877.0> connection <0.877.0> (172.18.0.4:57504 -> 172.18.0.2:5672): user 'guest' authenticated and granted access to vhost 'myvhost'
nitrate-worker-1      | [2022-03-30 21:54:00,629: INFO/MainProcess] Connected to amqp://guest:**@messagebus:5672/myvhost
nitrate-messagebus-1  | 2022-03-30 21:54:00.633 [info] <0.886.0> accepting AMQP connection <0.886.0> (172.18.0.4:57506 -> 172.18.0.2:5672)
nitrate-worker-1      | [2022-03-30 21:54:00,636: INFO/MainProcess] mingle: searching for neighbors
nitrate-messagebus-1  | 2022-03-30 21:54:00.636 [info] <0.886.0> connection <0.886.0> (172.18.0.4:57506 -> 172.18.0.2:5672): user 'guest' authenticated and granted access to vhost 'myvhost'
nitrate-messagebus-1  | 2022-03-30 21:54:00.649 [info] <0.903.0> accepting AMQP connection <0.903.0> (172.18.0.4:57508 -> 172.18.0.2:5672)
nitrate-messagebus-1  | 2022-03-30 21:54:00.652 [info] <0.903.0> connection <0.903.0> (172.18.0.4:57508 -> 172.18.0.2:5672): user 'guest' authenticated and granted access to vhost 'myvhost'
nitrate-web-1         |   Applying testplans.0004_remove_model_TestPlanActivity... OK
nitrate-web-1         |   Applying testplans.0005_add_nonexisting_email_settings_for_existing_plans... OK
nitrate-web-1         |   Applying testplans.0006_set_parent_null_when_delete_parent_plan... OK
nitrate-web-1         |   Applying testplans.0007_migration_due_to_add_related_name_to_model... OK
nitrate-web-1         |   Applying testplans.0008_remove_max_length_from_authfield... OK
nitrate-web-1         |   Applying testplans.0009_use_plural_of_testplan_attachment... OK
nitrate-web-1         |   Applying xmlrpc.0001_initial...2022-03-30 21:54:01,163 INFO tcms.core.apps: Change django_comments.object_pk to INTEGER in database nitrate
nitrate-web-1         |  OK
nitrate-web-1         | 2022-03-30 21:54:01,407 INFO entrypoint: Database is migrated successfully.
nitrate-web-1         | 2022-03-30 21:54:01,537 INFO entrypoint: Superuser admin is created successfully.
nitrate-worker-1      | [2022-03-30 21:54:01,664: INFO/MainProcess] mingle: all alone
nitrate-worker-1      | [2022-03-30 21:54:01,693: INFO/MainProcess] celery@e6d5effc7894 ready.
nitrate-web-1         | 2022-03-30 21:54:02,642 INFO entrypoint: Default groups are created and permissions are set to groups properly.
nitrate-web-1         | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
nitrate-web-1         | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
nitrate-web-1         | [Wed Mar 30 21:54:02.811607 2022] [lbmethod_heartbeat:notice] [pid 10:tid 10] AH02282: No slotmem from mod_heartmonitor
nitrate-web-1         | [Wed Mar 30 21:54:02.815033 2022] [mpm_prefork:notice] [pid 10:tid 10] AH00163: Apache/2.4.52 (Fedora Linux) mod_wsgi/4.9.0 Python/3.10 configured -- resuming normal operations
nitrate-web-1         | [Wed Mar 30 21:54:02.815078 2022] [core:notice] [pid 10:tid 10] AH00094: Command line: 'httpd -D FOREGROUND'
nitrate-web-1         | [Wed Mar 30 21:54:17.941700 2022] [wsgi:error] [pid 15:tid 15] [client 172.18.0.1:64862] Target WSGI script not found or unable to stat: /usr/lib/python3.9
nitrate-web-1         | 172.18.0.1 - - [30/Mar/2022:21:54:17 +0000] "GET / HTTP/1.1" 404 196
nitrate-web-1         | 172.18.0.1 - - [30/Mar/2022:21:54:19 +0000] "GET / HTTP/1.1" 404 196
nitrate-web-1         | [Wed Mar 30 21:54:19.670888 2022] [wsgi:error] [pid 15:tid 15] [client 172.18.0.1:64862] Target WSGI script not found or unable to stat: /usr/lib/python3.9
nitrate-web-1         | 172.18.0.1 - - [30/Mar/2022:21:54:20 +0000] "GET / HTTP/1.1" 404 196
nitrate-web-1         | [Wed Mar 30 21:54:20.307298 2022] [wsgi:error] [pid 15:tid 15] [client 172.18.0.1:64862] Target WSGI script not found or unable to stat: /usr/lib/python3.9`

**Comment by tkdchen** [comment]
This issue is fixed. Please try again.
