### ISSUE TITLE
Social Auth Provider requires URLS

### ISSUE THREAD

**Issue by carstencodes** [Nitrate/Nitrate#1095]
According to the [python-social-auth documentation](https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#urls-entries), the url patterns have to be extended to support social auth properly.

```python
urlpatterns = patterns('',
    ...
    url('', include('social_django.urls', namespace='social'))
    ...
)
```

Hence the `urls.py` of the nitrate should be extended like this:

```python
if "SOCIAL" in settings.ENABLED_AUTH_BACKENDS:
    urlpatterns += [ path("", include('social_django.urls', namespace='social')) ]
```

Otherwise, the namespace social cannot be resolved when compiling the login page (refer to [this](https://github.com/Nitrate/Nitrate/blob/b89b37309f00469428e0372166d8c4c804bd9d0d/src/templates/registration/login.html#L53) for details).

Would you accept a pull request?

**Comment by tkdchen** [comment]
> Would you accept a pull request?

Sure. Appreicated.
