### ISSUE TITLE
nitrate worker crashes on development deployment via podman compose

### ISSUE THREAD

**Issue by suntorytimed** [Nitrate/Nitrate#1124]
The nitrate worker container repeatedly crashes. It seems like redis is missing in the container:

AttributeError: 'NoneType' object has no attribute 'Redis'

I have adjusted the container-compose.yml provided in this project to use `quay.io/nitrate/web:4.13` and `quay.io/nitrate/worker:4.13` and deployed it via `podman-compose up -d`

The web container shows:
```
No custom config module is importable.

If the custom config module is expected to be importable, please check whether the directory containing the module is added to the PYTHONPATH already.
```
in the logs.

**Comment by suntorytimed** [comment]
configuration issue

**Comment by tkdchen** [comment]
Good to know it works for you now

**Comment by ces-truongvu** [comment]
@suntorytimed Can you share how to solve it? Thank you very much.

**Comment by suntorytimed** [comment]
@ces-truongvu if I remember correctly I just forgot to define the config file for this volume mount in the worker definition in the docker-compose setup:

```
volumes:
    - "./compose/custom_settings.py:/nitrate-config/nitrate_custom_conf.py:Z"
```
