### ISSUE TITLE
Rescue tests

### ISSUE THREAD

**Issue by tkdchen** [Nitrate/Nitrate#113]
We need to rescue the tests in each app.

- simplify the fixtures. Create required objects on-demand instead of using a JSON file to provide fixture data.
- Fix existent tests so that they are able to run. Rewrite some of them if necessary.

- [x] testplans
- [x] testcases
- [x] testruns
- [x] core
- [x] xmlrpc

**Comment by tkdchen** [comment]
Using a separate package to help creating fixtures, e.g. FactoryBoy, would be much convenient. That was used in a project I contributed before. In my mind, it's easy to create one or more model instances.

/cc @atodorov

**Comment by atodorov** [comment]
+1 for using FactoryBoy. I will look at my previous PR that deals with tests.

**Comment by tkdchen** [comment]
@atodorov do you have any idea how to use FactoryBoy to organize the fixture creation in Nitrate?

**Comment by atodorov** [comment]
Not at the moment. I will have to look at the entire test suite in more details to figure out what needs to be done. However this will not happen in the next 2 weeks probably b/c I will be travelling extensively.

**Comment by tkdchen** [comment]
Done
