### ISSUE TITLE
Issue with loading the Home page.

### ISSUE THREAD

**Issue by Rahulgowdagn1999** [Nitrate/Nitrate#1167]
Some times when i redirect to home page using Home button in the tab it gives 500 Service Error.

**Comment by tkdchen** [comment]
Can you please provide a reproduce steps, or any screenshot?

**Comment by Rahulgowdagn1999** [comment]
I have the attached screenshot.

**Comment by Rahulgowdagn1999** [comment]
[Uploading home page.pdf…]()
![Uploading 17177613591552023718668924845954.jpg…]()

**Comment by Rahulgowdagn1999** [comment]
![Uploading 20240607_172425.jpg…]()
