### ISSUE TITLE
Puggable email backend

### ISSUE THREAD

**Issue by atodorov** [Nitrate/Nitrate#134]
I'm opening this as a reminder to look at it. Currently Nitrate expect a mail service running on localhost if I'm not mistaken. I'm running Nitrate in the cloud and would like to configure it with SendGrid or Amazon SES. 

This issue is a reminder to take a look at the current settings and adjust the application if necessary.

**Comment by tkdchen** [comment]
Nitrate uses Django built-in [email mechanism](https://docs.djangoproject.com/en/1.8/topics/email/), which is configurable for sending emails via different SMTP servers.

If it does not meet your use case, it should be easy to write a customized backend on top of existing ones provided by Django.

**Comment by tkdchen** [comment]
Nitrate already supports plugable email backend based on Django's built-in email framework. At least, this is what the understand of "plugable" from current implementation. So, close this issue. If there is any new thoughts, feel free to keep discussing.
