### ISSUE TITLE
Create systemd service file for celeryd

### ISSUE THREAD

**Issue by tkdchen** [Nitrate/Nitrate#136]
A service file for celeryd is required in order to ensure Nitrate works well on newer version of Linux distributions that uses systemd. At this moment, I have no idea if such a service file is provided by celery officially. If not, we need to write one by ourselves.

**Comment by atodorov** [comment]
Why does Nitrate use Celery ? What is it used for?

**Comment by tkdchen** [comment]
Celery is used to do asynchronous tasks, IIRC, currently sending emails and updating bug are handled in Celery. However, it depends on the settings. If not set, Nitrate will use Python thread.

**Comment by tkdchen** [comment]
Celery is used by Nitrate to run jobs in parallel. But, in whichever environment where Nitrate is deployed, Celery should be configured separately by an infra team and Nitrate should not configure Celery by its own configuration file. So, I'm going to close this issue.
