### ISSUE TITLE
RFC: Split kerberos auth into a separate package

### ISSUE THREAD

**Issue by atodorov** [Nitrate/Nitrate#147]
@tkdchen I'd like to hear your comments on this. 

We don't use kerberos at all and I think it would be wise to split the code into its own package. I can do the split and also prepare another repository (titled nitrate-kerberos-auth or similar) which I can then transfer under the Nitrate organization. I will also update the docs and add instructions about how to enable kerberos auth if somebody needs it. These instructions will be the basis for documenting additional auth backends. I'm really interested in GitHub authentication for example.

This will help reduce the number of external dependencies we're pulling in and don't really use. 

How does the plan above sound to you ?

**Comment by tkdchen** [comment]
I guess you are talking about ``KerberosBackend`` and ``ModAuthKerbBackend``, right?. Only former has external dependency, which is ``kerberos`` module. I think it is unnecessary to split these into a separate package at current stage. If you don't need Kerberos authentication, just move the ``import kerberos`` into ``KerberosBackend``.

In the future, Nitrate will support other authentication mechanisms, in my mind, each of them should be plugable and configurable (probably for example enable, disable, set the default in Nitrate), but not in separate packages individually, they are simple enough and easy to maintain. If the authentication mechanism will be becoming complicated more and more, split could be considered at that time, but not now IMHO.

**Comment by atodorov** [comment]
I can see the benefit of having `KerberosBackend` and `ModAuthKerbBackend` inside the same source tree, makes it easier for testing and development. However since many people will not use them by default I think there's value of providing a mechanism to opt out of these by default. 

I don't really want the krb5-devel RPM and the kerberos PyPI package on my servers unless I use these, which I'm not. Same goes for MySQL as well btw. There are many reasons why you may not want to have unused packages on your system, security being one of them, also smaller Docker image sizes, etc.

I propose a small patch to `requirements/base.txt` which removes the kerberos dependency. Also update the docs to make it clear how to enable kerberos if desired. For example something like

    ... to enable kerberos authentication pip install kerberos and configure your settings.py as follows ...

@tkdchen how about this then ?

**Comment by tkdchen** [comment]
Kerberos authentication is now optional. To use it, install dependent kerberos module by `pip install .[krbauth]`. It is not installed by default, which also benefits the 3rd party package process, e.g. building RPM.
