### ISSUE TITLE
commit_unless_managed should be fixed

### ISSUE THREAD

**Issue by tkdchen** [Nitrate/Nitrate#148]
``commit_unless_managed`` is not available in Django 1.8 and later. It should be replaced with correct equivalent call in Django 1.8.

**Comment by tkdchen** [comment]
Part of #110

**Comment by atodorov** [comment]
After #159 is merged I can look into this since I already have some idea about this area in the code and already made progress adding some tests.

**Comment by tkdchen** [comment]
I have already started and part of them have been fixed. I can fix others except those in xmlrpc app you have done in #159.
