### ISSUE TITLE
Installing files under /etc yields SandboxViolation in virtualenv

### ISSUE THREAD

**Issue by atodorov** [Nitrate/Nitrate#155]
In one of my environments installing a newer version of Nitrate yields:
```
remote: error: Setup script exited with error: SandboxViolation: open('/etc/httpd/conf.d/nitrate-httpd.conf', 'wb') {}
```

this is due to the change made in ff4ecc75 adding the `data_files` attribute to `setup.py`. I propose installing these files under /etc via the RPM packages, not via pip.

**Comment by atodorov** [comment]
@tkdchen ping? This is a real problem in virtualenv or pretty much everywhere if you don't have root access. What's your take on it?

**Comment by tkdchen** [comment]
Should be fixed. Removing relative code from ``setup.py`` should make it work well.

**Comment by atodorov** [comment]
OK, sending a patch to fix `setup.py` shortly.
