### ISSUE TITLE
Detect and fix docstring quoted by 3 single quotes

### ISSUE THREAD

**Issue by atodorov** [Nitrate/Nitrate#165]
Many tests use `'''` for doc strings while they should be using `"""`. Before fixing them however I'd like to find a tool which can be configured to check for the desired style. `flake8`, `pep8` or something similar should do the trick, just need to research how to configure that exactly.

Side note: the same tool should check for 1 blank line between a class doc string and the next method. If you beat me to fixing the docstring quotes, please open another one for this item!

@tkdchen feel free to assign to me.

**Comment by tkdchen** [comment]
From my perspective, flake8 is good enough now. Not a tool is perfect to detect any potential problems. I think it's easy to remember to use double quote docstring and put one and only one blank line before each class method.
