### ISSUE TITLE
Replace request.REQUEST with request.GET or request.POST correctly

### ISSUE THREAD

**Issue by tkdchen** [Nitrate/Nitrate#173]
```
grep -rnH "request\.REQUEST" tcms/ | cut -d':' -f1 | uniq -c
```

- [x] 46 tcms/testcases/views.py
- [x]  2 tcms/templates/run/get.html
- [x]  1 tcms/templates/run/edit.html
- [x]  4 tcms/testplans/views.py
- [x]  7 tcms/testcases/actions.py
- [x]  2 tcms/core/utils/\_\_init__.py
- [x]  2 tcms/core/contrib/comments/views.py
- [x]  6 tcms/core/contrib/auth/views.py
- [x]  9 tcms/core/ajax.py
- [x]  2 tcms/core/views/search.py
- [x] 19 tcms/core/files.py
- [x]  2 tcms/profiles/views.py
- [x] 26 tcms/management/views.py
- [x] 64 tcms/testruns/views.py

Relative to #110

**Comment by atodorov** [comment]
@tkdchen we have 2 PRs related to this issue and they are becoming quite big. I propose working on them first and merging before we continue to fix the rest of the deprecations. The grep command you have provided is quite useful.

**Comment by tkdchen** [comment]
@atodorov I'm currently on ``19 tcms/core/files.py`` besides those commits in PR #176. What are you working on? Hope we don't have conflict with each other.

**Comment by tkdchen** [comment]
Done.
