### ISSUE TITLE
Refactor add/remove bug to use common implementation

### ISSUE THREAD

**Issue by atodorov** [Nitrate/Nitrate#184]
While working on https://github.com/Nitrate/Nitrate/pull/79 I have discovered that for adding and removing bugs we use separate code paths which are very similar. This applies both to the Python code and to the JavaScript code. These can be refactored to use a single implementation.

* Test Case Run add/remove bug uses `testruns.views.bug()` and its internal class `CaseRunBugActions` and from `tesrun_actions.js` -> `addCaseRunBug()`, `removeCaseRunBug()`, `updateBugsActionAdd()` and `updateBugsActionRemvoe()`
* Test Case, tab Bugs uses `testcases.views.bug()` and its internal class `CaseBugActions` and from `testcase_actions.js` -> `addCaseBug()` and `removeCaseBug()`.

**Comment by tkdchen** [comment]
I'll handle this, as it is also relative to #173 that is what I'm doing now.

**Comment by tkdchen** [comment]
I just realize that the scope of this issue is bigger than the fix of #173. So, I'll only fix the part of ``request.REQUEST``, and unassign this issue from me.
