### ISSUE TITLE
Improve integrations between Nitrate and bug tracking systems

### ISSUE THREAD

**Issue by atodorov** [Nitrate/Nitrate#185]
With the work done in #79 I have removed some bits which didn't make sense or need better implementation. With the introduction of arbitrary bug tracking systems we need a better way to figure out how to attach test cases to them, how to file bugs from Nitrate, etc.  

So far I'm thinking about providing some common integrations for the most popular bug trackers and let the user configure them in the UI (DB preferably) when they define their bug tracker of choice.
Here are some notes:

* In test case run, Add bug dialog, there was a `Check to add test cases to BZ` checkbox, see 
https://github.com/Nitrate/Nitrate/pull/79#r114034036. This checkbox is controlled via the `BUGZILLA_EXTERNAL_TRACKER` setting:
  * The setting only disables actions, doesn't hide the checkbox from UI, needs to be fixed
  * `tcms.integrations.bugzilla.signals.bugs.BZ_Externer_Track_Thread` appears to be similar to `tcms.integrations.bugzilla.tasks.bugzilla_external_track`
  * `bugzilla_external_track` doesn't read the bugzilla URL from the DB but instead relies on settings. We can improve this by storing this info into the DB and make it easier to configure via the UI.
 * This task seems to require celery and I don't recall seeing a section about celery or how to run celery nodes in the documentation. Also not everyone wants to use Celery and add external messaging layer for it so think about providing a simple implementation running on localhost (or maybe even in synchronous mode)
* In test case run, there is a "File" bug link, which is processed by `testruns.views.bug` and its internal class `CaseRunBugActions`. Currently this gives 500 ISE and needs to be reworked to support arbitrary bug trackers
* Test run bugs report page used to show Bugzilla & JIRA links at the bottom of the screen. These were links which open all reported bugs with one click, see https://github.com/Nitrate/Nitrate/pull/79#r114034413. This has been removed as part of #79 and needs to be added back but in a more clever way. 

I will be working on this next, but filing here so I don't forget all the details.

**NOTE** - the integration functions I mention above need to have the same public interface and live in a single module so that they can be easily extended.

**NOTE2** - unused settings like `BUGZILLA_*` and `JIRA_URL` need to be removed.

**Comment by tkdchen** [comment]
I'd like to mention two points at this moment,

- code in both UI and internal view and models should handle issue trackers from database. Ideally, in the end of this change improvement, all ``BUGZILLA_*`` and ``JIRA_*`` will not exist in settings.
- Celery can be enabled in production environment if someone wants to use it. However, by default, Nitrate changes bug information in a thread, IIRC which is also the way in development environment.

**Comment by tkdchen** [comment]
This would be a big change to Nitrate. I would suggest you could use a separate branch in your cloned repository for opening PR and even code review from that branch directly.

**Comment by tkdchen** [comment]
Additional thoughts

- all things related to issue tracker should go to a separate module directory, it is probably named ``issuetracker``.
- the database schema and code should be easier for extension to support other issue trackers as much as possible.
- change issues in an external issue tracker would require authentication, like current Bugzilla support in Nitrate, so this should be cared about very carefully. Currently, only need to change bug in a Bugzilla, and not change a JIRA issue.

**Comment by tkdchen** [comment]
If you like, you can fix relative issue #151 with this issue together.

**Comment by tkdchen** [comment]
![nitrate-issuetracker](https://cloud.githubusercontent.com/assets/919706/25563291/692d0ea6-2dcb-11e7-8da8-dd5fc65bcf02.jpg)

Basically, issuetracker has this simple relationship. ``Issue`` should be a contenttype that can have relationship  to either ``TestCase`` or ``TestCaseRun``, but no need to store case_id or test_case_run_id in ``Issue`` that is what Nitrate does now and it's really bad.

**Comment by atodorov** [comment]
@tkdchen thanks for the comments, I will look at them. Do you mind merging #79 first so that I can base this new work on the existing changes ?

**Comment by tkdchen** [comment]
Is d225198 ready for review or just WIP?
