### ISSUE TITLE
Errata field visible when ERRATA_URL_PREFIX is empty string

### ISSUE THREAD

**Issue by atodorov** [Nitrate/Nitrate#186]
When editting a Test Run there is an Errata field visible even though the ERRATA_URL_PREFIX setting is an empty string. Also this isn't documented properly from what I can tell.

1) The Errata edit field needs to be hidden if the setting is not configured
2) In test run view template the field should be hidden if not visible
3) Admin guide needs to say what an errata system is and how it is used in Nitrate
4) Also there is some messaging integration under `tcms.integrations.errata` which at least needs to be documented

NOTE: except the integration this errata info is used only to produce a clickable link which really feels the same as attaching a bug tracker URL to the test run. Also given the proposed changes in #185 I think we can refactor this template to actually use a Bug tracker link and its corresponding integrations.

**Comment by atodorov** [comment]
3), 4) and NOTE moved to https://github.com/Nitrate/Nitrate/issues/189

**Comment by tkdchen** [comment]
Refer to #378
