### ISSUE TITLE
Testrun new.html and edit.html are very similar

### ISSUE THREAD

**Issue by atodorov** [Nitrate/Nitrate#190]
Both templates share similar properties and they can probably be merged into a single template to reduce layout duplication. 

Also IMO it is best to move templates under their respective app directories instead of having all of them under one single directory.

**Comment by tkdchen** [comment]
Although there is similar part in both a test run new and edit page, there are different code to control different display for creating a new run and editing an existing run respectively. Merging the similar part into one template could introduce a few `if-else` in template to display the different parts for creation and edit. This looks make no sense. Just keeping the template there without any change for this issue.
