### ISSUE TITLE
Tutorial\doc improvements

### ISSUE THREAD

**Issue by GodfatherThe** [Nitrate/Nitrate#230]
I'm trying to install and run Nitrate, but I have some questions which I cannot find answer in documentation:
- set_dev_env_with_vagrant.rst - what is the username for admin? How do I create new admin user after everything is up and running? None of `django-admin createsuperuser --settings tcms.settings`, `django-admin createsuperuser --settings tcms.settings.product`, `django-admin createsuperuser --settings settings` works :(

**Comment by GodfatherThe** [comment]
Found some solution, put it along with other notes in PR #231

**Comment by tkdchen** [comment]
Can you be more specific on "I'm trying to install and run Nitrate". According to what I understand from literally, you are not in the right way to install and run Nitrate. Vagrant is only for development purpose, even Nitrate can run inside the virtual machine, it is only for development and debug. Probably, other documents about installation might be the ones you need.

**Comment by tkdchen** [comment]
As mentioned before, please try the new Vagrantfile. Again, please do not treat the Nitrate in virtual machine created by Vagrant for normal use. It's only for development purpose.
