### ISSUE TITLE
Default admin user / password

### ISSUE THREAD

**Issue by dbo2qa** [Nitrate/Nitrate#277]
After following the tutorial for Vagrant, I can access Nitrate now. However, I didn't know what is the default Admin username / password. Cannot find that information from the guide.
Please help me on this. Thanks

**Comment by tkdchen** [comment]
The last provision step is `Set superuser's password to admin`. Default password is `admin`. This information is in `testenv.yml`.

**Comment by dbo2qa** [comment]
Great! Thanks for the information
