### ISSUE TITLE
django-preserialize requires django<1.11, Nitrate uses 1.11.11

### ISSUE THREAD

**Issue by nugatorium** [Nitrate/Nitrate#311]
Running through the required installation methods for Nitrate I run:
`sudo python setup.py install`

and I get 

`Processing dependencies for Nitrate==4.1
error: Django 1.11.11 is installed but django<1.11,>=1.8 is required by set(['django-preserialize'])`

The requirements.txt file shows:
`Django=1.11.11
...
django-preserialize==1.2.1`

Should I change the Django version down to 1.10.xx?

**Comment by braveswang** [comment]
I think you should uninstall Django 1.11.11, or create a python virtualenv to install django 1.8 for nitrate 4.1

**Comment by atodorov** [comment]
You can also try https://demo.kiwitcms.org which is running latest Django 2

**Comment by tkdchen** [comment]
@nugatorium Yes, you can change to use Django 1.10.x.
