### ISSUE TITLE
支持xmind 的用例导入导出吗？

### ISSUE THREAD

**Issue by lvfengwen** [Nitrate/Nitrate#330]
如题，does it support xmind filetype to upload and download?

**Comment by tkdchen** [comment]
尚未支持。xmind用例是什么样的？不了解这个。

**Comment by tkdchen** [comment]
能给个用xmind描述的测试用例的例子吗？

**Comment by tkdchen** [comment]
@lvfengwen  我近期在尝试xmind8，你说的xmind是这个吗？用xmind怎么写测试用例，导出的格式是什么？
