### ISSUE TITLE
docker installation on mac not working

### ISSUE THREAD

**Issue by 87abhii** [Nitrate/Nitrate#398]
tar: Error is not recoverable: exiting now
ERROR: Service 'web' failed to build: The command '/bin/sh -c mkdir /code                                                         &&     cd /tmp                                                             &&     curl -L -O ${VCS_URL}/archive/v${VERSION}.tar.gz                    &&     tar xf /tmp/v${VERSION}.tar.gz --directory /code                    &&     mv /code/Nitrate-${VERSION}/* /code                                 &&     rm /tmp/v${VERSION}.tar.gz' returned a non-zero code: 2

as soon as i run docker -compose up the following error comes
any help how to run docker thanks

**Comment by tkdchen** [comment]
Hi, you need to pass `4.3` to `VERSION` via option `--build-arg`. The docker images do actually have some issues, which have been fixed.

There are actually several ways to run Nitrate inside container. Please refer to https://nitrate.readthedocs.io/en/latest/install/index.html

**Comment by 87abhii** [comment]
Hi thanks for responding :
-all good but cannot exceute this step
-docker exec -it nitrate_web_1 /code/src/manage.py migrate
-docker exec -it nitrate_web_1 /code/src/manage.py createsuperuser

PXT7972TA13MAC:Nitrate user$ docker exec -it nitrate_web_1 /Nitrate/src/manage.py migrate
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"/Nitrate/src/manage.py\": stat /Nitrate/src/manage.py: no such file or directory": unknown
PXT7972TA13MAC:Nitrate user$ 

and on web page :http://localhost:8001/

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by tkdchen** [comment]
> docker exec -it nitrate_web_1 /code/src/manage.py migrate

This is incorrect actually. It is fixed already in the document. Please retry again with the updated commands in section https://nitrate.readthedocs.io/en/latest/install/docker.html#initial-configuration-of-running-container

**Comment by 87abhii** [comment]
Fixed thanks a lot application is up 
Great
Have another issue in import but for that i will raise another issue 
thanks a lot
