### ISSUE TITLE
Upgrade supported version of Python and Django

### ISSUE THREAD

**Issue by tkdchen** [Nitrate/Nitrate#4]
Nitrate was being developed with old version of Python and Django for a long time. Now, we have no reason to keep these old technologies continously, no matter the enhancement supplied by newer release of Python and Django, or the security fixes especially from Django that should benefit any potential users.

Propose version of Python is 2.7, then Django version is 1.7.1 that is the latest released version as of writing this issue.

I have to say I'm not much radical to use most latest technology. That will introduce various problems to either development team and users. Supporting current widely-used technologies is accpetable. Meanwhile, a stable and explicit regular upgrade policy is important.

**Comment by atodorov** [comment]
see also #81

**Comment by atodorov** [comment]
@AdamWill Django versions in Fedora are very old and they are also incompatible with 1.8.X and latest 1.9 and even 1.10. I propose closing this issue and either bring the latest Django RPMs to Fedora or using a virtualenv if you still use Nitrate. 

Btw some of the other dependencies don't appear to be available in Fedora at all (or not in their latest version).

**Comment by tkdchen** [comment]
There is ``python2-django-1.9.12-1.fc24.noarch``. I'm happy to build other dependencies in Fedora if necessary after upgrading to Django 1.9.

**Comment by tkdchen** [comment]
Close this issue since Django has be upgraded to 1.8 in master.

**Comment by AdamWill** [comment]
F24 and F25 have Django 1.9; Rawhide has Django 1.10. Anything older than that is unsupported.

However, we're not *currently* actively looking at using Nitrate for Fedora QA, which was my initial interest in this, so I don't have a high priority for this issue ATM.
