### ISSUE TITLE
"GET /accounts/login/ HTTP/1.1" 500 27

### ISSUE THREAD

**Issue by daniel418** [Nitrate/Nitrate#466]
Hi,
After  run nitrate server  encounter "GET /accounts/login/ HTTP/1.1" 500 27 on host side after visit http://localhost:8086.And the browser displayed "Server Error (500)",How can I debug? thanks

qa@qa /var/www/html/Nitrate/src/tcms/settings (develop *=) $ django-admin.py runserver 0.0.0.0:8086 --settings=tcms.settings.product
Performing system checks...

System check identified no issues (0 silenced).
November 25, 2019 - 06:07:57
Django version 2.2.7, using settings 'tcms.settings.product'
Starting development server at http://0.0.0.0:8086/
Quit the server with CONTROL-C.
[25/Nov/2019 06:08:16] "GET /accounts/login/ HTTP/1.1" 500 27
[25/Nov/2019 06:08:19] "GET /accounts/login/ HTTP/1.1" 500 27

**Comment by daniel418** [comment]
Follow https://blog.csdn.net/tkdchen/article/details/102538857 , this issue could be fixed.

**Comment by tkdchen** [comment]
The first try could be set `debug = True` on the top of file `tcms/settings/product.py` and restart the server. Then, once some error happens, you will get a traceback in the browser instead.

**Comment by tkdchen** [comment]
No response for months. Close this issue for now. Feel free to reopen if the issue happens again.
