### ISSUE TITLE
XMLRPC Auth.login does not work with django.contrib.auth.backends.ModelBackend

### ISSUE THREAD

**Issue by tash** [Nitrate/Nitrate#498]
Calls to Auth.login always return with ''Wrong username or password'' when django.contriub.auth.backends.ModelBackend is used.

https://github.com/Nitrate/Nitrate/blob/2c3c60826730687ccb3e9347bf15798074926dd7/src/tcms/xmlrpc/api/auth.py#L46

This call is wrong, as it takes a request object as first object: https://docs.djangoproject.com/en/3.0/ref/contrib/auth/#django.contrib.auth.backends.ModelBackend.authenticate

Possible fix based on the django documentation

> request is an HttpRequest and may be None if it wasn’t provided to authenticate() (which passes it on to the backend).

`user = backend.authenticate(None, *check_user_name(credential))`

**Comment by tash** [comment]
The request argument was added in Django 1.11. This bug should be reproducible for all newer versions of Django.

**Comment by tkdchen** [comment]
Hi @tash, thanks for reporting this issue. Would you mind open a PR for this issue?

**Comment by tash** [comment]
Will do once I gave time.
