### ISSUE TITLE
use class-based view instread funciton-based view.

### ISSUE THREAD

**Issue by BrickXu** [Nitrate/Nitrate#51]
Lots of view functions handle GET and POST both, it is not a good practice, need to do some refactoring to split GET and POST into different method.

**Comment by tkdchen** [comment]
Yeah. Lots of code of Nitrate have been live for several years. Migrate all FBV to CBV will give huge benefit to Nitrate to make life better in the new generation.

**Comment by tkdchen** [comment]
This should be a best practice for developing a new view. But, it looks makes no sense to keep this issue open always. So, close for now.

时光荏苒，都已经马上快2022了。 :smile:

**Comment by BrickXu** [comment]
雄哥还在坚持，加油
