### ISSUE TITLE
migrate nitrate from django1.5 to 1.7

### ISSUE THREAD

**Issue by BrickXu** [Nitrate/Nitrate#52]
__CheckList__:

* New application registry logic, need to handle the duplicated labels in INSTALLED_APPS. Refs https://docs.djangoproject.com/en/1.7/ref/applications/

* Upgrade 3rd libs.

* schema migrate scripts.

* Nitrate custom comments app will cause "maximum recursion depth exceeded" error.

* django.utils.simplesjon was removed, use json or simplejson instead.

**Comment by tkdchen** [comment]
duplicated #4 

is it possible to be compatible with 1.6 and 1.7?

**Comment by tkdchen** [comment]
@BrickXu any further updated information?

**Comment by atodorov** [comment]
see also #81

**Comment by tkdchen** [comment]
duplicate. So, close it.
