### ISSUE TITLE
What do following options mean when clone cases?

### ISSUE THREAD

**Issue by tkdchen** [Nitrate/Nitrate#67]
- Copy the component to new product you specific (Unchecking will remove component of copied test case)
- Copy the attachments to new product you specific (Unchecking will remove attachments of copied test case)

@jianchen2580

**Comment by jianchen2580** [comment]
If "Copy component" checked, the components which belong to origin testcase(s) will add to new testcase(s).
If "Copy attacments" checked, the attachments will cloned (create new TestCaseAttachment record here) and attached to new testcase(s).

**Comment by tkdchen** [comment]
>  If "Copy attacments" checked, the attachments will cloned (create new TestCaseAttachment record here) and attached to new testcase(s).

do not make a copy of the attachment file, right?
