### ISSUE TITLE
Update Django to latest version of 1.8.x

### ISSUE THREAD

**Issue by tkdchen** [Nitrate/Nitrate#69]

**Comment by atodorov** [comment]
see also #81

**Comment by tkdchen** [comment]
As of writing this comment, latest version of 1.8 is 1.8.11. This is also the version in Fedora repository. 1.9.x is good choice, but for Nitrate, 1.8.x is enough.

**Comment by tkdchen** [comment]
duplicate with #4

**Comment by tkdchen** [comment]
It is in master already. https://github.com/Nitrate/Nitrate/commit/d4f815f600c772afa9ec7ce7c7aaa52b1cce3cad
