### ISSUE TITLE
I can't type in some chinese words when I write the tescases or plans

### ISSUE THREAD

**Issue by fengwubeixue** [Nitrate/Nitrate#727]
nitrate:4.4
Run inside Container

![image](https://user-images.githubusercontent.com/67784078/88646370-a6abd500-d0f7-11ea-953d-e88b8efe3421.png)

**Comment by tkdchen** [comment]
@fengwubeixue 你的数据库使用的编码是什么？能把你启动container的命令贴出来吗？

**Comment by fengwubeixue** [comment]
> @fengwubeixue 你的数据库使用的编码是什么？能把你启动container的命令贴出来吗？

数据库编码应该是默认的utf8的，我尝试去修改，在docker-compose.yml中增加，MYSQL_CHARSET= utf8mb4
            MYSQL_COLLATION=utf8mb4_unicode_ci，但貌似不生效，是不是容器再次docker-compose up的时候数据库已经生成了，编码格式不会变了？容器是用docker compose启动的，docker-compose.yml文件我基本上没改动，贴在下面，


version: "3"

# Please note that, this docker-compose is only for test latest image built
# from development branch and prod image built from released version.
# Before launching database and Nitrate images, make sure the image is built by
# `make image' with proper tag.
#
# If you would like to launch Nitrate for development purpose, please use
# `docker-compose-dev.yml`.

services:
  db:
    image: "mariadb:10.4.12"
    volumes:
    - "nitrate_db_data:/var/lib/mysql"
    restart: always
    environment:
    - MYSQL_DATABASE=nitrate
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  web:
    depends_on:
    - db
    restart: always
    image: "${DOCKER_ORG:-quay.io/nitrate}/nitrate:${IMAGE_VERSION:-latest}"
    ports:
    - "8000:8000"
    volumes:
    - "nitrate_uploads:/code/uploads"
    - "nitrate_httpd_logs:/var/log/httpd"
    environment:
      NITRATE_DB_ENGINE: mysql
      NITRATE_DB_HOST: db
      NITRATE_DB_PORT: 3306
      NITRATE_DB_NAME: nitrate
      NITRATE_DB_USER: root

# Run `docker inspect web` to see volume directory on host.

volumes:
  nitrate_db_data:
  nitrate_uploads:
  nitrate_httpd_logs:

**Comment by tkdchen** [comment]
> 是不是容器再次docker-compose up的时候数据库已经生成了

@fengwubeixue 应该是，可以试着删除db的容器以及关联的volume。你先试着改一下字符编码，看能不能正常工作。我一直是使用pgsql，还真没注意到这个问题。一般来说，个人推荐使用pgsql。这几天有时间我按照你的方法试试看能否重现你的问题。

**Comment by tkdchen** [comment]
@fengwubeixue 目前最新版本是4.7.2。4.4有点太老了。

**Comment by fengwubeixue** [comment]
我也想用新版的，用容器跑4.7.2的我也试过了，会出现其他的问题，如下图，删db的容器我试试看
![image](https://user-images.githubusercontent.com/67784078/88871554-c273c000-d24a-11ea-97dc-d3f3dd658b17.png)

**Comment by tkdchen** [comment]
@fengwubeixue Hi, 久等了。你的这个问题已经修了。首先你得在develop分支上运行`git pull`，然后再运行：

```bash
export IMAGE_VERSION=4.7.2
docker-compose up
docker-compose run -e DJANGO_SETTINGS_MODULE=tcms.settings.product web /bin/bash -c "
django-admin migrate
django-admin setdefaultperms
django-admin createsuperuser --username <your username> --email <email address>
"
```

到这就可以使用了 http://127.0.0.1:8001/

**Comment by tkdchen** [comment]
No response from reporter. Please try the new image. If there is still any problem related to this issue, please reopen, or open a new issue for it.
