### ISSUE TITLE
Cannot install base requirements

### ISSUE THREAD

**Issue by apollo13** [Nitrate/Nitrate#99]
You are trying to install wadostuff from `https://wadofstuff.googlecode.com/files/wadofstuff-django-serializers-1.1.0.tar.gz#egg=wadofstuff-django-serializers` which no longer works. Since this is only needed for such an old Django version, I think it makes sense to vendor https://github.com/mattimustang/wadofstuff/tree/master/python/serializer till you can move to 1.8

**Comment by apollo13** [comment]
Matthew Flanagan was kind enough to upload the latest version to Pypi, so you can switch the requirement to use PyPi instead. Also celery & related packages need pinning for version < 4.

**Comment by tkdchen** [comment]
I've been playing with Nitrate to upgrade Django to 1.9.x. wadofstuff-django-serializers was removed and replaced with django-preserialize. Those changes is in my personal repository now.

https://github.com/tkdchen/Nitrate/blob/upgrade-django/requirements/base.txt#L14

**Comment by tkdchen** [comment]
Close this issue, since wadofstuff-django-serializers is already replaced with django-preserialize.
